[package]
name = "stunt-service"
version = "0.1.3"
edition = "2024"

description = "A declarative web framework for Rust/Wasm"
readme = "../../README.md"
authors = ["proxin"]
repository = "https://github.com/proxin187/stunt"
keywords = ["web", "javascript", "gui", "wasm", "webasm"]
categories = ["gui", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
erased-serde = "0.4.6"
serde_json = "1.0.143"
serde = { version = "1.0.219", features = ["derive"] }
ureq = { version = "3.1.2", features = ["json"] }

