[package]
name = "stunt-macro"
version = "0.1.2"
edition = "2024"

description = "Built-in macros for stunt"
readme = "../../README.md"
authors = ["proxin"]
repository = "https://github.com/proxin187/stunt"
keywords = ["web", "javascript", "gui", "wasm", "webasm"]
categories = ["gui", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["full"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
